<?php
session_start();
require '../includes/connection.php';
require '../libraries/fpdf/fpdf.php';

// Validate session
if (!isset($_SESSION['email']) || ($_SESSION['role'] != 'Cashier' && $_SESSION['role'] != 'Superadmin')) {
    header("Location: ../../index.php");
    exit();
}

// Get query parameters
$selectedDate = isset($_GET['date']) ? $_GET['date'] : date('Y-m-d');
$showWholeMonth = isset($_GET['whole_month']) && $_GET['whole_month'] == '1';

// Initialize
$dailyRevenue = [];
$totalRevenue = 0;

// Prepare SQL
$selectedMonth = date('m', strtotime($selectedDate));
$selectedYear = date('Y', strtotime($selectedDate));
$selectedDay = date('d', strtotime($selectedDate));

if ($showWholeMonth) {
    $sql = "SELECT DAY(transaction_date) AS day, SUM(amount) AS total_revenue
            FROM transactions
            WHERE transaction_type = 'Load' AND MONTH(transaction_date) = ? AND YEAR(transaction_date) = ?
            GROUP BY DAY(transaction_date)";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param('ii', $selectedMonth, $selectedYear);
} else {
    $sql = "SELECT SUM(amount) AS total_revenue
            FROM transactions
            WHERE transaction_type = 'Load' AND DATE(transaction_date) = ?";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param('s', $selectedDate);
}

$stmt->execute();
$result = $stmt->get_result();

if ($showWholeMonth) {
    $dailyRevenue = array_fill(1, 31, 0);
    while ($row = $result->fetch_assoc()) {
        $dailyRevenue[(int)$row['day']] = (float)$row['total_revenue'];
    }
} else {
    $dailyRevenue[(int)$selectedDay] = 0;
    if ($row = $result->fetch_assoc()) {
        $dailyRevenue[(int)$selectedDay] = (float)$row['total_revenue'];
    }
}

$stmt->close();
$totalRevenue = array_sum($dailyRevenue);

// Generate PDF
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(0, 10, 'Daily Revenue Report', 0, 1, 'C');

$pdf->SetFont('Arial', '', 12);
$pdf->Cell(0, 10, 'Generated by: ' . $_SESSION['firstname'] . ' ' . $_SESSION['lastname'], 0, 1);
$pdf->Cell(0, 10, 'Date: ' . date('F d, Y', strtotime($selectedDate)), 0, 1);

$pdf->Ln(5);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(30, 10, 'Day', 1);
$pdf->Cell(60, 10, 'Revenue (PHP)', 1);
$pdf->Ln();

$pdf->SetFont('Arial', '', 12);
foreach ($dailyRevenue as $day => $revenue) {
    if ($showWholeMonth || $day == (int)$selectedDay) {
        $pdf->Cell(30, 10, $day, 1);
        $pdf->Cell(60, 10, number_format($revenue, 2), 1);
        $pdf->Ln();
    }
}

$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(30, 10, 'Total', 1);
$pdf->Cell(60, 10, number_format($totalRevenue, 2), 1);

$pdf->Output('D', 'Revenue_Report_' . $selectedDate . '.pdf');
exit();
